sonar.projectKey=arslanGH840_cohort-9-mern-14578-arslan
sonar.organization=arslangh840
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.js,**/*.test.jsx,**/database/migrations/**,**/database/seeders/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info